name: Build IPA

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install kivy
        pip install git+https://github.com/kivy/kivy-ios.git
        pip install -r requirements.txt

    - name: Install system dependencies
      run: |
        brew install autoconf automake libtool pkg-config
        brew link libtool

    - name: Cache Kivy-ios toolchain
      uses: actions/cache@v2
      id: kivy-ios-cache
      with:
        path: kivy_ios_venv
        key: ${{ runner.os }}-kivy-ios-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-kivy-ios-

    - name: Build the Kivy-ios toolchain
      if: steps.kivy-ios-cache.outputs.cache-hit != 'true'
      run: |
        python -m venv kivy_ios_venv
        source kivy_ios_venv/bin/activate
        pip install --upgrade pip
        pip install cython==0.29.17
        pip install git+https://github.com/kivy/kivy-ios.git
        kivy_ios_venv/bin/python -m kivy_ios.toolchain build python3
        APP_NAME="MyKivyApp"
        kivy_ios_venv/bin/python -m kivy_ios.toolchain create $APP_NAME $APP_NAME
        cp main.py $APP_NAME-ios/$APP_NAME/main.py
        kivy_ios_venv/bin/python -m kivy_ios.toolchain update $APP_NAME-ios
        deactivate

    - name: List Xcode schemes
      run: |
        APP_NAME="MyKivyApp"
        cd $APP_NAME-ios
        xcodebuild -list

    - name: Build IPA
      run: |
        APP_NAME="MyKivyApp"
        SCHEME_NAME="mykivyapp"
        cd $APP_NAME-ios
        xcodebuild archive -scheme $SCHEME_NAME -archivePath $APP_NAME.xcarchive
        xcodebuild -exportArchive -archivePath $APP_NAME.xcarchive -exportOptionsPlist ExportOptions.plist -exportPath ./IPA

    - name: Upload IPA as artifact
      uses: actions/upload-artifact@v2
      with:
        name: MyKivyApp
        path: MyKivyApp-ios/IPA/MyKivyApp.ipa