name: Compile Files (iOS)

on:
  workflow_run:
    workflows: ["Test Python Script"]
    types:
      - completed

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install kivy-ios

    - name: Build Kivy project for iOS
      run: |
        APP_NAME="CryptoSeedProject"
        kivy-ios -m pip install kivy
        kivy-ios create "$APP_NAME" com.github.crypto-seed-project

    - name: Build IPA
      run: |
        APP_NAME="CryptoSeedProject"
        SCHEME_NAME="cryptoseedproject"
        cd "$APP_NAME-ios"
        xcodebuild archive -scheme $SCHEME_NAME -archivePath "$APP_NAME.xcarchive" CODE_SIGNING_ALLOWED=NO CODE_SIGN_IDENTITY=""
        xcodebuild -exportArchive -archivePath "$APP_NAME.xcarchive" -exportOptionsPlist ExportOptions.plist -exportPath ./IPA CODE_SIGNING_ALLOWED=NO CODE_SIGN_IDENTITY=""
      shell: bash

    - name: Upload IPA
      uses: actions/upload-artifact@v2
      with:
        name: CryptoSeedProject
        path: CryptoSeedProject-ios/CryptoSeedProject.ipa
