name: Compile Files (PC)

on:
  workflow_run:
    workflows: ["Test Python Script"]
    types:
      - completed

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest', 'ubuntu-latest', 'macos-latest']

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - run: pip install -r requirements.txt pyinstaller

    # Get version
    - name: Get version
      shell: bash
      run: echo "VERSION=$(python main.py -v true)" | tee -a $GITHUB_ENV

    # Define the names for each operating system
    - name: Define names
      shell: bash
      run: |
        if [ "${{ matrix.os }}" == "windows-latest" ]; then
          OS_NAME="Windows"
        elif [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
          OS_NAME="Ubuntu"
        else
          OS_NAME="MacOS"
        fi
        FILE_NAME="Build_${OS_NAME}-${VERSION}"
        echo "FILE_NAME=$FILE_NAME" | tee -a $GITHUB_ENV

    # Run the application on different operating systems
    - name: Run on Windows
      if: matrix.os == 'windows-latest'
      shell: cmd
      run: |
        pyinstaller --onefile --name %FILE_NAME% main.py
        .\dist\%FILE_NAME% -t true

    - name: Run on Ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: |
        pyinstaller --onefile --name $FILE_NAME.bin main.py
        ./dist/$FILE_NAME.bin -t true

    - name: Run on MacOS
      if: matrix.os == 'macos-latest'
      run: |
        pyinstaller --onefile --name $FILE_NAME.app main.py
        ./dist/$FILE_NAME.app -t true

    # Upload the artifact
    - name: Upload artifact for Windows
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.VERSION }}
        path: |
          dist/*
          dist\*

    - name: Upload artifact for Linux or MacOS
      if: matrix.os != 'windows-latest'
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.VERSION }}
        path: |
          dist/${{ env.FILE_NAME }}.*