name: Compile Files (Debian)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: debian:10

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Python and dependencies
      run: |
        apt-get update
        apt-get install -y python3 python3-pip
        python3 -m pip install --upgrade pip
        pip3 install -r requirements.txt
        pip3 install pyinstaller
    - run: pip install -r requirements.txt pyinstaller

    # Get version
    - name: Get version
      shell: bash
      run: echo "VERSION=$(python main.py -v true)" | tee -a $GITHUB_ENV

    # Define the names for each operating system
    - name: Define names
      shell: bash
      run: |
        FILE_NAME="Debian-${VERSION}-x86_64"
        echo "FILE_NAME=$FILE_NAME" | tee -a $GITHUB_ENV

    - name: Compile Python script
      run: |
        pyinstaller --onefile main.py

    - name: Upload compiled executable
      uses: actions/upload-artifact@v2
      with:
        name: artifact
        path: dist/main
