name: Compile Files

on:
  workflow_run:
    workflows: ["Test Python Script"]
    types:
      - completed

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest', 'ubuntu-latest', 'macos-latest']

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - run: pip install -r requirements.txt pyinstaller

    # Get version
    - name: Get version
      shell: bash
      run: echo "VERSION=$(python main.py -v true)" | tee -a $GITHUB_ENV

    # Define the names for each operating system
    - name: Define names
      shell: bash
      run: |
        if [ "${{ matrix.os }}" == "windows-latest" ]; then
          OS_NAME="Windows"
        elif [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
          OS_NAME="Ubuntu"
        else
          OS_NAME="MacOS"
        fi
        FILE_NAME="${OS_NAME}-${VERSION}-x86_64"
        echo "FILE_NAME=$FILE_NAME" | tee -a $GITHUB_ENV

    # Run the application on different operating systems
    - name: Run on Windows
      if: matrix.os == 'windows-latest'
      shell: cmd
      run: |
        pyinstaller --onefile --name %FILE_NAME% main.py
        .\dist\%FILE_NAME% -t true

    - name: Run on Ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: |
        pyinstaller --onefile --name $FILE_NAME.bin main.py
        ./dist/$FILE_NAME.bin -t true

    - name: Run on MacOS
      if: matrix.os == 'macos-latest'
      run: |
        pyinstaller --onefile --name $FILE_NAME.app main.py
        ./dist/$FILE_NAME.app -t true

    # Upload the artifact
    - name: Upload artifact for Windows
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.VERSION }}
        path: |
          dist/*
          dist\*

    - name: Upload artifact for Linux or MacOS
      if: matrix.os != 'windows-latest'
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.VERSION }}
        path: |
          dist/${{ env.FILE_NAME }}.*

  build-debian:
    runs-on: ubuntu-latest
    container:
      image: debian:10

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Python and dependencies
      run: |
        apt-get update
        apt-get install -y python3 python3-pip
        python3 -m pip install --upgrade pip
        pip3 install -r requirements.txt
        pip3 install pyinstaller
    - run: pip install -r requirements.txt pyinstaller

    # Get version
    - name: Get version
      shell: bash
      run: echo "VERSION=$(python3 main.py -v true)" | tee -a $GITHUB_ENV

    # Define the names for each operating system
    - name: Define names
      shell: bash
      run: |
        FILE_NAME="Debian-${VERSION}-x86_64"
        echo "FILE_NAME=$FILE_NAME" | tee -a $GITHUB_ENV

    - name: Compile Python script
      run: |
        pyinstaller --onefile --name $FILE_NAME.bin main.py
        ./dist/$FILE_NAME.bin -t true

    - name: Upload artifact
      if: matrix.os != 'windows-latest'
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.VERSION }}
        path: |
          dist/${{ env.FILE_NAME }}.*

  build-alpine:
    runs-on: ubuntu-latest
    container:
      image: alpine:3.14

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Python and dependencies
      run: |
        apk update
        apk add python3 py3-pip binutils
        python3 -m pip install --upgrade pip
        pip3 install -r requirements.txt
        pip3 install pyinstaller
    - run: pip install -r requirements.txt pyinstaller

    # Get version
    - name: Get version
      shell: sh
      run: echo "VERSION=$(python3 main.py -v true)" | tee -a $GITHUB_ENV

    # Define the names for each operating system
    - name: Define names
      shell: sh
      run: |
        FILE_NAME="Alpine-${VERSION}-x86_64"
        echo "FILE_NAME=$FILE_NAME" | tee -a $GITHUB_ENV

    - name: Compile Python script
      run: |
        pyinstaller --onefile --name $FILE_NAME.bin main.py
        ./dist/$FILE_NAME.bin -t true

    - name: Upload artifact
      if: matrix.os != 'windows-latest'
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.VERSION }}
        path: |
          dist/${{ env.FILE_NAME }}.*

  build-centos:
    runs-on: ubuntu-latest
    container:
      image: centos:7

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Python and dependencies
      run: |
        yum install -y python3 python3-pip
        python3 -m pip install --upgrade pip
        pip3 install -r requirements.txt
        pip3 install pyinstaller
    - run: pip install -r requirements.txt pyinstaller

    # Get version
    - name: Get version
      shell: bash
      run: echo "VERSION=$(python3 main.py -v true)" | tee -a $GITHUB_ENV

    # Define the names for each operating system
    - name: Define names
      shell: bash
      run: |
        FILE_NAME="CentOS-${VERSION}-x86_64"
        echo "FILE_NAME=$FILE_NAME" | tee -a $GITHUB_ENV

    - name: Compile Python script
      run: |
        pyinstaller --onefile --name $FILE_NAME.bin main.py
        ./dist/$FILE_NAME.bin -t true

    - name: Upload artifact
      if: matrix.os != 'windows-latest'
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.VERSION }}
        path: |
          dist/${{ env.FILE_NAME }}.*

  build-fedora:
    runs-on: ubuntu-latest
    container:
      image: fedora:34

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Python and dependencies
      run: |
        dnf install -y python3 python3-pip binutils
        python3 -m pip install --upgrade pip
        pip3 install -r requirements.txt
        pip3 install pyinstaller
    - run: pip install -r requirements.txt pyinstaller

    # Get version
    - name: Get version
      shell: bash
      run: echo "VERSION=$(python3 main.py -v true)" | tee -a $GITHUB_ENV

    # Define the names for each operating system
    - name: Define names
      shell: bash
      run: |
        FILE_NAME="Fedora-${VERSION}-x86_64"
        echo "FILE_NAME=$FILE_NAME" | tee -a $GITHUB_ENV

    - name: Compile Python script
      run: |
        pyinstaller --onefile --name $FILE_NAME.bin main.py
        ./dist/$FILE_NAME.bin -t true

    - name: Upload artifact
      if: matrix.os != 'windows-latest'
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.VERSION }}
        path: |
          dist/${{ env.FILE_NAME }}.*

  build-raspbian:
    runs-on: ubuntu-latest
    container:
      image: balenalib/raspberry-pi-python:3.7-buster-build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Print OS information
      run: |
        echo "ID information:"
        cat /etc/*release | grep ^ID

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install -r requirements.txt
        pip3 install pyinstaller

    - name: Get version
      shell: bash
      run: echo "VERSION=$(python3 main.py -v true)" | tee -a $GITHUB_ENV

    - name: Define names
      shell: bash
      run: |
        FILE_NAME="Raspbian-${VERSION}-armhf"
        echo "FILE_NAME=$FILE_NAME" | tee -a $GITHUB_ENV

    - name: Compile Python script for ARM
      run: |
        pyinstaller --onefile --name $FILE_NAME.bin main.py
        ./dist/$FILE_NAME.bin -t true

    - name: Upload artifact
      if: matrix.os != 'windows-latest'
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.VERSION }}
        path: |
          dist/${{ env.FILE_NAME }}.*


