name: Compile and Upload main.py with NixOS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Nix package
      run: |
        docker pull nixos/nix
        docker run --rm -v $PWD:/app -w /app nixos/nix sh -c '
          printf "{ pkgs ? import <nixpkgs> {} }:\n\nlet\n  python = pkgs.python38;\n  nuitka = python.pkgs.nuitka;\nin pkgs.stdenv.mkDerivation rec {\n  pname = \"my-python-app\";\n  version = \"0.1.0\";\n\n  src = ./.;\n\n  buildInputs = [ python nuitka ];\n\n  buildPhase = \"\"\"\n    python -m nuitka --follow-imports main.py --output-dir=$out --unstripped --remove-output\n  \"\"\";\n\n  installPhase = \"\"\"\n    mkdir -p $out/bin\n    cp main.bin $out/bin/main\n  \"\"\";\n\n  meta = with pkgs.stdenv.lib; {\n    description = \"My Python application compiled with Nuitka\";\n    maintainers = with maintainers; [ ];\n  };\n}\n" > default.nix
          nix-build; \
          tar czvf result.tar.gz result'

    - name: Upload Nix package
      uses: actions/upload-artifact@v2
      with:
        name: my-python-app.nix
        path: result.tar.gz
