name: Compile Files

on:
  push:
    branches: [ "compile-test" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest', 'ubuntu-latest', 'macos-latest']

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.7

    # Define the names for each operating system
    - name: Define names
      shell: bash
      run: |
        if [ "${{ matrix.os }}" == "windows-latest" ]; then
          FILE_NAME="main_windows.exe"
        elif [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
          FILE_NAME="main_linux"
        else
          FILE_NAME="main_macos.app"
        fi
        echo "FILE_NAME=$FILE_NAME" | tee -a $GITHUB_ENV
        echo "FILE_NAME=$FILE_NAME" | Out-File -Append $env:GITHUB_ENV

    - run: pip install -r requirements.txt pyinstaller
    - run: pyinstaller --onefile --name=$FILE_NAME main.py
    
    - name: Get version
      shell: bash
      run: echo "VERSION=$(python main.py -v true)" | tee -a $GITHUB_ENV

    # Run the application on different operating systems
    - name: Run on Windows
      if: matrix.os == 'windows-latest'
      run: |
          .\dist\$FILE_NAME -t true

    - name: Run on Linux
      if: matrix.os == 'ubuntu-latest'
      run: |
        ./dist/$FILE_NAME -t true

    - name: Run on MacOS
      if: matrix.os == 'macos-latest'
      run: open dist/$FILE_NAME


    # Upload the artifact
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.VERSION }}
        path: |
          dist/$FILE_NAME

