name: Compile Files

on:
  push:
    branches: [ "compile-test" ]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest', 'ubuntu-latest', 'macos-latest']

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - run: pip install -r requirements.txt pyinstaller
    - run: pyinstaller --onefile main.py
    - name: Get version
      run: echo "VERSION=$(python main.py -v true)" >> $GITHUB_ENV
    # Optionally verify that it works (provided that it does not need user interaction)
    - name: Run on Windows
      if: matrix.os == 'windows-latest'
      run: |
        .\dist\main.exe -t true
    - name: Run on Linux or macOS
      if: matrix.os != 'windows-latest'
      run: |
        ./dist/main -t true
    - name: Upload artifact for Windows
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v2
      with:
        name: windows-artifact-v${{ env.VERSION }}
        path: dist/*
    - name: Upload artifact for Ubuntu
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v2
      with:
        name: ubuntu-artifact-v${{ env.VERSION }}
        path: dist/*
    - name: Upload artifact for macOS
      if: matrix.os == 'macos-latest'
      uses: actions/upload-artifact@v2
      with:
        name: macos-artifact-v${{ env.VERSION }}
        path: dist/*
