name: Build and Push Docker Image

on:
  push:
    branches: [ "*" ]

env:
  DOCKER_IMAGE_NAME: exohayvan/crypto-seed-project
  DOCKER_IMAGE_TAG: latest
  REGISTRY: ghcr.io
  IMAGE_NAME: exohayvan/crypto-seed-project

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Login to GitHub Packages
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: |
            # Base image
            FROM python:3.9.9-bullseye

            # Set working directory
            WORKDIR /app

            # Copy requirements file
            COPY requirements.txt .

            # Install dependencies
            RUN pip install --no-cache-dir -r requirements.txt

            # Copy application code
            COPY . .

            # Run the script
            CMD [ "python3", "main.py" ]
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }}
