name: Build and Push Docker Image

on:
  push:
    branches:
      - main

env:
  DOCKER_IMAGE_NAME: exohayvan/crypto-seed-project
  DOCKER_IMAGE_TAG: latest
  DOCKER_BUILD_CONTEXT: .

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to GitHub Packages
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GIT_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ${{ env.DOCKER_BUILD_CONTEXT }}
          push: true
          tags: docker.pkg.github.com/${{ github.repository }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }}
