name: Compile Files

on:
  push:
    branches: [ "compile-test" ]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest', 'ubuntu-latest', 'macos-latest']

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - run: pip install -r requirements.txt pyinstaller
    - run: pyinstaller --onefile main.py
    - name: Get version
      run: echo "VERSION=$(python main.py -v true)" >> $GITHUB_ENV
    - name: Rename and archive
      run: |
        os_name=""
        case "${{ matrix.os }}" in
          windows-latest) os_name="Windows" ;;
          ubuntu-latest) os_name="Ubuntu" ;;
          macos-latest) os_name="macOS" ;;
        esac
        file_ext=""
        [ "${{ matrix.os }}" == "windows-latest" ] && file_ext=".exe"
        mv "dist/main${file_ext}" "dist/${os_name}_${VERSION}${file_ext}"
        tar czf "dist/${VERSION}.tar.gz" -C dist "${os_name}_${VERSION}${file_ext}"
    # Optionally verify that it works (provided that it does not need user interaction)
    - name: Run on Windows
      if: matrix.os == 'windows-latest'
      run: |
        .\dist\Windows_${{ env.VERSION }}.exe -t true
    - name: Run on Linux or macOS
      if: matrix.os != 'windows-latest'
      run: |
        ./dist/$(echo "${{ matrix.os }}" | cut -d'-' -f1)_${{ env.VERSION }} -t true
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.os }}-artifact-${{ env.VERSION }}
        path: dist/${{ env.VERSION }}.tar.gz
