name: Create Release

on:
  workflow_run:
    workflows: ["Compile Files (PC)", "Compile Files (Debian)"]
    types:
      - completed

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Find and download artifact
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          artifacts=$(curl --silent --header "Authorization: token $GITHUB_TOKEN" "https://api.github.com/repos/${{ github.repository }}/actions/artifacts")
          artifact_url=$(echo "$artifacts" | jq -r '.artifacts[0].archive_download_url')
          
          if [ -n "$artifact_url" ]; then
            echo "Downloading artifact from $artifact_url"
            curl -L --header "Authorization: token $GITHUB_TOKEN" --header "Accept: application/vnd.github+json" --remote-name --location "$artifact_url"
            unzip -o "$(basename "$artifact_url")" -d artifacts

            # Compress each file into a separate .zip archive
            for file in artifacts/*; do
              base_name=$(basename "$file")
              echo "Compressing $base_name"
              zip -r "artifacts/${base_name%.*}.zip" "$file"
              rm -f "$file"
            done
          else
            echo "No artifacts found"
            exit 1
          fi

      - name: Get version and artifact names
        shell: bash
        run: |
          VERSION=$(python main.py -v true)
          ARTIFACT_NAMES=$(ls artifacts/* | tr '\n' ',')
          echo "VERSION=$VERSION" | tee -a $GITHUB_ENV
          echo "ARTIFACT_NAMES=$ARTIFACT_NAMES" | tee -a $GITHUB_ENV

      - name: Check if release exists and artifacts are uploaded
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Checking release and artifacts for version: ${{ env.VERSION }}"
    
          releases=$(curl --silent --header "Authorization: token $GITHUB_TOKEN" "https://api.github.com/repos/${{ github.repository }}/releases")
    
          existing_release_info=$(echo "$releases" | jq -r --arg version "${{ env.VERSION }}" '.[] | select(.tag_name == $version) // ""')
          echo "Existing release info:"
          echo "$existing_release_info"
    
          if [ -n "$existing_release_info" ]; then
            echo "Release ${{ env.VERSION }} already exists, checking artifacts."
            existing_assets=$(echo "$existing_release_info" | jq -r '.assets | map(.name) | join(",")')
            echo "Existing assets: $existing_assets"

            missing_assets=""
            IFS=',' read -ra ADDR <<< "$ARTIFACT_NAMES"
            for asset_path in "${ADDR[@]}"; do
              asset_name=$(basename $asset_path)
              echo "Checking asset: $asset_name"
              if [[ $existing_assets != *"$asset_name"* ]]; then
                missing_assets+="$asset_path,"
              fi
            done
            missing_assets=${missing_assets%?}
            echo "MISSING_ASSETS=$missing_assets" | tee -a $GITHUB_ENV
          fi

      - name: Generate Changelog
        run: |
          set -x
          releases=$(curl --silent --header "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/releases")
          latest_release_info=$(echo "$releases" | jq -r 'sort_by(.created_at) | reverse | .[0]')
          latest_release_tag=$(echo "$latest_release_info" | jq -r '.tag_name // ""')

          git fetch --tags --unshallow || true
          git fetch origin main

          if [ -z "$latest_release_tag" ]; then
            echo "No previous release found. Generating changelog from the beginning."
            changelog=$(git log --pretty=format:"- %s (%h)" -- main.py)
          else
            echo "Generating changelog since the latest release: $latest_release_tag"
            changelog=$(git log "$latest_release_tag..HEAD" --pretty=format:"- %s (%h)" -- main.py)
          fi
          added_changes=$(echo "$changelog" | grep -Ei "(Add(ed)?|New)" || true)
          removed_changes=$(echo "$changelog" | grep -Ei "Remove(d)?" || true)
          fixed_changes=$(echo "$changelog" | grep -Ei "Fix(ed)?" || true)

          echo "Added:" > changelog.txt
          if [ -z "$added_changes" ]; then
            echo "N/A" >> changelog.txt
          else
            echo "${added_changes}" | sed -E 's/(Add(ed)?|New)/ /I' >> changelog.txt
          fi
          echo " " >> changelog.txt
    
          echo "Removed:" >> changelog.txt
          if [ -z "$removed_changes" ]; then
            echo "N/A" >> changelog.txt
          else
            echo "${removed_changes}" | sed -E 's/Remove(d)?/ /I' >> changelog.txt
          fi
          echo " " >> changelog.txt
    
          echo "Fixed Issues:" >> changelog.txt
          if [ -z "$fixed_changes" ]; then
            echo "N/A" >> changelog.txt
          else
            echo "${fixed_changes}" | sed -E 's/Fix(ed)?/ /I' >> changelog.txt
          fi
          echo " " >> changelog.txt
    
          echo "[Known Issues](https://github.com/${{ github.repository }}/issues?q=is%3Aissue+milestone%3A${{ env.VERSION }})" >> changelog.txt

      - name: Urlencode VERSION
        id: urlencode
        run: |
          urlencode() {
            local string="${1}"
            local strlen="${#string}"
            local encoded=""
            for (( pos=0 ; pos<strlen ; pos++ )); do
              local c="${string:$pos:1}"
              case "$c" in
                [-_.~a-zA-Z0-9] ) encoded+="$c" ;;
                * ) printf -v encoded '%s%%%02X' "$encoded" "'$c"
              esac
            done
            echo "$encoded"
          }
          encoded_version=$(urlencode "${{ env.VERSION }}")
          echo "ENCODED_VERSION=$encoded_version" | tee -a $GITHUB_ENV

      - name: Upload missing artifacts to existing release
        if: ${{ env.MISSING_ASSETS != '' && env.MISSING_ASSETS != 'null' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          release_id=$(echo "$existing_release_info" | jq -r '.id')
          IFS=',' read -ra ADDR <<< "$MISSING_ASSETS"
          for asset in "${ADDR[@]}"; do
            echo "Uploading $asset to existing release"
            curl -v \
              -X POST \
              -H "Authorization: token $GITHUB_TOKEN" \
              -H "Accept: application/vnd.github+json" \
              -F "file=@$asset;type=$(file -b --mime-type $asset)" \
              "https://uploads.github.com/repos/Exohayvan/Crypto-Seed-Project/releases/$release_id/assets?name=$(basename $asset)"
          done

      - name: Create Release
        if: ${{ env.MISSING_ASSETS == '' || env.MISSING_ASSETS == 'null' }}
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.VERSION }}
          release_name: ${{ env.VERSION }}
          body_path: changelog.txt
          draft: false
          prerelease: ${{ contains(env.VERSION, 'alpha') || contains(env.VERSION, 'beta') }}

      - name: Attach artifacts to the release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          IFS=',' read -ra ADDR <<< "$ARTIFACT_NAMES"
          for asset in "${ADDR[@]}"; do
            echo "Uploading $asset to release"
            curl \
              --request POST \
              --header "Authorization: token $GITHUB_TOKEN" \
              --header "Content-Type: $(file -b --mime-type $asset)" \
              --data-binary @$asset \
              "https://uploads.github.com/repos/${{ github.repository }}/releases/${{ steps.create_release.outputs.id }}/assets?name=$(basename $asset)"
          done
