# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Test Python Script

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

permissions:
  contents: read

jobs:
  build:
    name: run script
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Python and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3 python3-pip
        python3 -m pip install --upgrade pip
        pip3 install -r requirements.txt
        OPENSSL_CONF=/etc/ssl/openssl.cnf
        grep -q 'openssl_conf\s*=\s*openssl_init' $OPENSSL_CONF || echo 'openssl_conf = openssl_init' | sudo tee -a $OPENSSL_CONF
        grep -q '\[openssl_init\]' $OPENSSL_CONF || echo -e '\n[openssl_init]' | sudo tee -a $OPENSSL_CONF
        grep -q 'legacy_provider\s*=\s*legacy_provider_section' $OPENSSL_CONF || echo 'legacy_provider = legacy_provider_section' | sudo tee -a $OPENSSL_CONF
        grep -q '\[legacy_provider_section\]' $OPENSSL_CONF || echo -e '\n[legacy_provider_section]\nactivate = 1' | sudo tee -a $OPENSSL_CONF


    - name: Test
      run: |
        pip install pytest requests
        python3 main.py -t true
