# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Test Python Script

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

permissions:
  contents: read

jobs:
  build:
    name: run script
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Python and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3 python3-pip
        python3 -m pip install --upgrade pip
        pip3 install -r requirements.txt
        echo -e "\n[engines]\nripemd160 = openssl_engine" | sudo tee -a /etc/ssl/openssl.cnf

    - name: Test
      run: |
        pip install pytest requests
        python3 main.py -t true
